spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/frederick
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true
        #default_batch_fetch_size: 100
    #open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 10
        one-indexed-parameters: true
logging:
  level:
    org.hibernate.SQL: info
    #org.hibernate.type: info
